### ISSUE TITLE
Invalid certificate error for docs.cider.mx

### ISSUE THREAD

**Issue by loopified** [clojure-emacs/docs.cider.mx#1]
When clicking the link to the docs in CIDER's description, both Firefox 67 and Chromium 73 block the page from rendering and display warnings.

![image](https://user-images.githubusercontent.com/9657386/58427602-9f221380-808f-11e9-8690-38669f26f9de.png)

Visiting https://cider.mx directly doesn't give me this error (although it blocks the automatic redirect to https://cider.mx/cider/index.html but this may be due to my browsers configuration).

**Comment by bbatsov** [comment]
I've launched a new site earlier today and I guess I messed up the DNS config. No idea why the CNAME record doesn't work properly. I'll investigate this further when I can.

**Comment by loopified** [comment]
Just tested it and it seems like the links to the documentation on Cider's README have been correctly homogenized and are valid, so I guess this is a closed issue. Thank you!
